# This is a basic workflow to help you get started with Actions

name: Hello World
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   hello-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo text
        run: 'echo "Hello, world! this is my first workflowfile"'
